name: A sample PR Sanity workflow
on: 
  workflow_dispatch:
jobs:
  build:
    name: prSanityBuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          path: ${GITHUB_WORKSPACE}
          VAR1: "Value of var1."
        env:
          ENV1: "Value Of environment variable env1."
      - name: init
        id: init
        shell: bash
        run: |
          run: |
          java -version
          mvn --version
          #ls -lart